### ISSUE TITLE
i only have proxy-kali.c how do i change it in to .sh?

### ISSUE THREAD

**Issue by eliecer696** [th3unkn0n/adfly_bot#1]

**Comment by th3unkn0n** [comment]
It's C progrm ...

**Comment by eliecer696** [comment]
how do i run it

**Comment by eliecer696** [comment]
also am geting this error frome the bot.py 

Traceback (most recent call last):
  File "/root/Desktop/adfly_bot-master/bot.py", line 20, in <module>
    requests.get("http://"+x, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //clesolea.com/4R1r (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573efeaad0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by th3unkn0n** [comment]
Yo have to compile C 
gcc proxy-kali.c -o proxy-kali

In bot.py
If you r using link with http or https :
Change this line :
requests.get("http://"+x, headers=headers)
TO :
requests.get(x, headers=headers)

**Comment by eliecer696** [comment]
after compiling it and running the new one it gives me this './proxy-kali: �o��Y�m7�ws-E�8-����o᛺exec '%s' "$@"

**Comment by th3unkn0n** [comment]
Are you on termux or kali linux  ?

**Comment by eliecer696** [comment]
kali

**Comment by th3unkn0n** [comment]
Used install.sh ??

**Comment by eliecer696** [comment]
yea it did't gave me any erros it run just fine

**Comment by eliecer696** [comment]
can you compile the proxy-kali and upload it pleas ?
